User handling
suttacentral/elastic-bilara pull request #7
Opened 2023-07-10 04:42 UTC by matkrzeminski

These changes allow for:
- Logging in with GitHub.
- Adding a users.json of this format: `[
    {
        "github_id": int,
        "username": str,
        "email": str,
        "avatar_url": str,
        "role": str
    }
]` which is used for the permissions and users data in general.
- Using access and refresh JWT.
- Adding Roles for users (proofreader and translator logic for now).

2023-07-10 05:09 UTC, marekbryling requested changes

2023-07-10 05:09 UTC, marekbryling commented on .env.example
> +GITHUB_CLIENT_SECRET=change_me
Missing empty line

2023-07-10 05:09 UTC, marekbryling commented on Makefile
> +	@$(COMPOSE) exec bilara-backend pytest /app/app/tests
Missing empty line

2023-07-10 07:31 UTC, marekbryling approved these changes

2023-07-10 07:40 UTC, merged

2023-07-17 10:31 UTC, mkorlaga commented on backend/app/services/users/utils.py
> +    return username == muid.split("-", 2)[2]
`-` can be used in github username, muid.split() can eventually lead to not full username

2023-07-17 10:33 UTC, mkorlaga commented on backend/app/services/auth/utils.py
> +    )
This forces us to check what is the `get_credentials_exception` - creating separate file for exceptions and creating new one based on HTTPException would be more clear `class UnauthorizedException`

2023-07-17 10:34 UTC, mkorlaga commented on backend/app/services/users/schema.py
> +    role: str = "proofreader"
This can be enumed from `backend/app/services/users/roles.py`